### PR TITLE
Add MathNet MKL provider

### PR DESCRIPTION
**Pull request by PhilPJL**
Using the MathNet Intel MKL provider pushes MathNet up into 3rd place.

image

### CODE REVIEW

**Comment by wo80** [comment]
According to Intel benchmarks it should actually be faster than FFTW - at least on an Intel CPU. So I guess it's the complex FFT?

Thanks for the PR, but I don't think, I'll merge it:
1) There already are benchmarks comparing MKL FFT and FFTW, so the results are not surprising.
2) MathNet v5 decoupled the the native MKL library from the provider, so you'd have to add another package reference, for example `MathNet.Numerics.MKL.Win-x64` for x64. This would then pull another ~50MB and would fail on Linux.
3) Though MKL is freely available, I'd like to restrict the benchmark to open source implementations.

**Comment by wo80** [comment]
Ignoring point 3, you could add a test to check whether MKL is available like I did with FFTW, see [Util.sc](https://github.com/wo80/SharpFFTW/blob/master/fftbench/fftbench.Common/Util.cs#L23). So at least the benchmark wouldn't crash, when the native library isn't found.

And don't add a package reference to `MathNet.Numerics.MKL.Win-x64`. Just add a note to `README.md` to let the users know to add the package they need, in case they want to include MKL in the benchmark.

**Comment by PhilPJL** [comment]
No problem.  It does the trick for me though.

**Comment by TSerious** [comment]
I've extended the original project here: [TSerious/FFTBench](https://github.com/TSerious/FFTBench)
If you want to @PhilPJL you can add Math.Net+MKL and FFTWF to the project.

**Pull request closed without merging**
